name: Lint

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Make sure commit messages follow the conventional commits convention:
  # https://www.conventionalcommits.org
  commitlint:
    name: Lint Commit Messages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: wagoid/commitlint-github-action@v6.2.1

  prek:
    name: Run prek checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Run prek
        uses: j178/prek-action@v2

  # test:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version:
  #         - "3.14"
  #       os:
  #         - ubuntu-latest
  #         # - windows-latest
  #         # - macOS-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - uses: actions/checkout@v6
  #     - name: Install uv
  #       uses: astral-sh/setup-uv@v5
  #       with:
  #         enable-cache: true
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - name: Install Dependencies
  #       run: uv sync --all-extras
  #       shell: bash
  #     - name: Test with Pytest
  #       run: uv run pytest
  #       shell: bash
